#!/bin/sh

APP_CENTRAL_DIR=/usr/local/AppCentral

HTTPD_DIR=$(find $APP_CENTRAL_DIR -maxdepth 1 -type d -name 'httpd-*' -print -quit)

APACHE2=$HTTPD_DIR/data/binary/sbin/apache2

# If web server is down, restart the server.
if ! pidof apache2 > /dev/null
then
    echo `date +"[%Y-%m-%d %T GMT]"` "Server down"
    echo `date +"[%Y-%m-%d %T GMT]"` "restarting Apache2 server.."
    $APACHE2 -k restart > /dev/null
    sleep 10
 
    #checking if apache restarted or not
    if pidof apache2 > /dev/null
    then
        echo `date +"[%Y-%m-%d %T GMT]"` "Apache stopped on Molib Stage. Automatically restarted succesfully."
    else
        echo `date +"[%Y-%m-%d %T GMT]"` "Apache stopped on Molib Stage. Automatically restart failed. Please check manually."
    fi
fi
