#!/bin/sh

BASE_DIR=/usr/builtin/etc/certificate
CRT_DIR=$BASE_DIR/ssl

# Asustor Web SSL certification list file location
CRT_FILE=$BASE_DIR/certificate.json

# Display help for command line arguments
helpFunction()
{
    echo ""
    echo "Usage: $0 -d domainName"
    echo -e "\t-d Domain name"
    exit 1 # Exit script after printing help
}

# Get all the argument passed from the command line
while getopts "d:" opt
do
   case "$opt" in
      d ) domainName="$OPTARG" ;;
      ? ) helpFunction ;; # Print helpFunction in case parameter is non-existent
   esac
done

# Print helpFunction in case parameters are empty
if [ -z "$domainName" ]
then
   echo "Please provide the domain name";
   helpFunction
fi

php -r "
print ("tes");
"

# Get the domain SSL certification ID from the certification list
CRT_DATA=$(php -r '
    $cert=json_decode(file_get_contents("'$CRT_FILE'"), true);
    
    foreach($cert["cert_list"] as $key)
    {
        if(in_array("'$domainName'", explode(",", $key["alt_name"])))
        {
            print("{\n");
            print("\"id\":\"$key[id]\",\n");
            print("\"domain_name\":\"'$domainName'\",\n");
            print("\"crt_dir\":\"'$CRT_DIR'/$key[id]\",\n");
            print("\"valid_time\":\"$key[valid_time]\",\n");
            print("}");
        }
    }
')

echo $CRT_DATA
